/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOFTEndpointGetter } from "./IOFTEndpointGetter";
export type { RewardDistributorV1LZ } from "./RewardDistributorV1LZ";
