/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IOFTEndpointGetterInterface extends utils.Interface {
  functions: {
    "endpoint()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "endpoint"): FunctionFragment;

  encodeFunctionData(functionFragment: "endpoint", values?: undefined): string;

  decodeFunctionResult(functionFragment: "endpoint", data: BytesLike): Result;

  events: {};
}

export interface IOFTEndpointGetter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOFTEndpointGetterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    endpoint(
      overrides?: CallOverrides
    ): Promise<[string] & { iEndpoint: string }>;
  };

  endpoint(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    endpoint(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    endpoint(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    endpoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
