/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOFTEndpointGetter,
  IOFTEndpointGetterInterface,
} from "../../../../contracts/mocks/RewardDistributorV1LZMock.sol/IOFTEndpointGetter";

const _abi = [
  {
    inputs: [],
    name: "endpoint",
    outputs: [
      {
        internalType: "contract ILayerZeroEndpointV2",
        name: "iEndpoint",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOFTEndpointGetter__factory {
  static readonly abi = _abi;
  static createInterface(): IOFTEndpointGetterInterface {
    return new utils.Interface(_abi) as IOFTEndpointGetterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOFTEndpointGetter {
    return new Contract(address, _abi, signerOrProvider) as IOFTEndpointGetter;
  }
}
