/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenProxy,
  ITokenProxyInterface,
} from "../../../contracts/interfaces/ITokenProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "enum ITokenControllerCommons.LockTime",
        name: "_lock",
        type: "uint8",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenProxy__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenProxyInterface {
    return new utils.Interface(_abi) as ITokenProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenProxy {
    return new Contract(address, _abi, signerOrProvider) as ITokenProxy;
  }
}
